name: Deploy API to Azure App Service

on:
  push:
    branches:
      - deploy
    paths:
      - "API/**"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: restore-api # Your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: "API"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/api
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/api
